# Generated by DeployHub — review exposed port and start command before deploying.

FROM composer:2 AS vendor
WORKDIR /app
COPY composer.json composer.lock* ./
RUN composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs --no-scripts

FROM php:8.4-cli-alpine
WORKDIR /var/www/html
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
RUN apk add --no-cache icu-libs libzip \
  && apk add --no-cache --virtual .build-deps $PHPIZE_DEPS icu-dev libzip-dev oniguruma-dev \
  && docker-php-ext-install -j$(nproc) pdo_mysql mbstring zip opcache \
  && apk del .build-deps
COPY --from=vendor /app/vendor ./vendor
COPY . .
RUN composer dump-autoload --optimize --no-dev --no-interaction \
  && mkdir -p storage/framework/{cache/data,sessions,views,testing} storage/logs storage/app/{public,private} bootstrap/cache \
  && php -r "file_exists('database/database.sqlite') || touch('database/database.sqlite');" \
  && php scripts/fix-permissions.php \
  && chown -R www-data:www-data storage bootstrap/cache database || true
EXPOSE 80
CMD ["php","artisan","serve","--host=0.0.0.0","--port=80"]
