apiVersion: v1
kind: Service
metadata:
  name: demo-php-project
  namespace: demo-php-project-production
spec:
  type: ClusterIP
  selector:
    app: demo-php-project
  ports:
  - port: 80
    targetPort: 80
